spring:
    datasource:
        username: postgres
        password: linktree123
        url: jdbc:postgresql://linktree-db-instance.czwc8kayugg1.us-east-1.rds.amazonaws.com:5432/linktree_db 
    sql:
        init:
            mode: always  